version: '3.8'
services:
  app:
    environment:
      - DJANGO_DEBUG=1
      - DJANGO_SECRET_KEY=devserver
      - TEAMPLAYER_WALK=/usr/share/music
      - PYTHONPATH=/usr/src/teamplayer

    volumes:
      - .:/usr/src/teamplayer
      - $HOME/Music:/usr/share/music


  database:
    ports:
      - 5432:5432

    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
