# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-18 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tp_library', '0002_genre_null_true'),
    ]

    operations = [
        migrations.AlterField(
            model_name='songfile',
            name='genre',
            field=models.TextField(blank=True, null=True),
        ),
    ]
