"""TeamPlayer URL dispatcher"""
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'teamplayer.views',
    url(r'^about', 'about'),
    url(r'^teamplayer\.js$', 'js_object'),
    url(r'^crash/$', 'crash'),
    url(r'^artist/(?P<artist>.*)/image$', 'artist_image'),
    url(r'^artist/(?P<artist>.*)$', 'artist_page'),
    url(r'^queue/$', 'show_queue'),
    url(r'^queue/add$', 'add_to_queue'),
    url(r'^queue/shuffle$', 'randomize_queue'),
    url(r'^queue/order_by_rank$', 'order_by_rank'),
    url(r'^queue/toggle$', 'toggle_queue_status'),
    url(r'^auto/toggle$', 'toggle_auto_mode'),
    url('^reorder_queue$', 'reorder_queue'),
    url(r'^queue/(\d+)$', 'show_entry'),
    url(r'^player.html$', 'player'),
    url(r'^players/$', 'show_players'),
    url(r'^registration/$', 'registration'),
    url(r'^register/$', 'register'),
    url(r'^logout$', 'logout'),
    url(r'^currently_playing$', 'currently_playing'),
    url(r'^change_dj_name$', 'change_dj_name'),
    url(r'^stations/$', 'show_stations'),
    url(r'^stations/(\d+|mine)$', 'station_detail'),
    url(r'^$', 'home'),
    url(r'^station/(\d+)/', 'home', name='station'),
    url(r'^station/prev', 'previous_station'),
    url(r'^station/next', 'next_station'),
    url(r'^station/edit', 'edit_station'),
    url(r'^station/create', 'create_station'),
)
