# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-11 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [("teamplayer", "0006_add_playlog_model")]

    operations = [
        migrations.AddField(
            model_name="entry",
            name="album",
            field=models.CharField(max_length=254, null=True),
        )
    ]
