version: '2'
services:
    wsgi:
        build: teamplayer
        depends_on:
            - database

        ports:
            - "8000-8099:8000-8099"

        environment:
            - DJANGO_DEBUG

        volumes:
            - ../..:/usr/src/teamplayer

    database:
        image: postgres:9.6
        environment:
            - POSTGRES_HOST_AUTH_METHOD=trust

    web:
        image: nginx
        depends_on:
            - wsgi

        ports:
            - "80:80"

        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro

        volumes_from:
            - wsgi:ro

